# Generated by Django 3.0.8 on 2021-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210712_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='job',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
