# Generated by Django 3.2.5 on 2021-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210725_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
