# Generated by Django 3.2.5 on 2021-08-14 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_financial_record_investigation_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial_record',
            name='item',
        ),
        migrations.AddField(
            model_name='financial_record',
            name='investigation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='item_paid_for', to='main.investigation_request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investigation_request',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
